version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - todo-network

  frontend:
    build:
      context: ./Frontend/Todo front
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    depends_on:
      - backend
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data: